services:
  api:
    build: 
      context: ../../
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network

  app:
    build: 
      context: ../../
      dockerfile: code/deployment/app/Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
